### ISSUE TITLE
Number woes?

### ISSUE THREAD

**Issue by hikatja** [josh-collinsworth/slothy#1]
When running this script two numbers issues are encountered:

1. The sourceTotal total sum disagrees with the sourceTotal sum for each listing. Using the readme as an example: the total number of errors is 12952, while the sum of each listing is 13455.

2. The percentage breakdown is inaccurate (rounding error?). Using the readme as an example, the total of all percentages is 103.9%.

**Comment by josh-collinsworth** [comment]
I can't speak to #1 at the moment, but #2 is the result of some (possibly many) slow errors mentioning more than one plugin and/or theme.

It's common for the total to exceed 100% (and even, in some cases, for the top two errors to total almost 200%) because the percentage is merely the percentage of errors which mention the given plugin or theme. 

For example: if 98% of my slow errors mention both my theme and WooCommerce, you'll see that 98% are my theme, and 98% are WooCommerce—seemingly implying 196%. But in reality, this just means that each one of those two things are implicated 98% of the time.

**Comment by josh-collinsworth** [comment]
Actually, it looks like #1 stems from the same issue, which is probably a valid concern. "Total errors" (non-intuitively) counts the hits for plugins/themes, rather than the total number of error blocks. That probably shouldn't be the case.

#2, though, is working as intended for reasons explained above.

**Comment by josh-collinsworth** [comment]
Looks like this is actually working as intended. Both number mismatches can be explained by the fact that one error _block_ may mention more than one plugins and/or themes.

The total number of plugins/themes mentioned will very likely be higher than the total number of error blocks, and the percentages will likely total more than 100% because of this.

**Comment by hikatja** [comment]
Okay, well, that's unintuitive, but thanks for confirming!
